# -*- coding: utf-8 -*-
"""hypothesis_testing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvWe8jBMm5xyGBzJPB-KxCnnCjFx7v0G
"""

import math
from scipy.stats import norm

def z_test_critical(mean_h0, sample_avg, pop_std, size_n, sig_level=0.05, test_type=1):
    # Compute standard error
    std_error = pop_std / math.sqrt(size_n)

    # TWO-TAILED TEST
    if test_type == 1:
        z_crit = norm.ppf(1 - sig_level / 2)
        lower_cv = mean_h0 - z_crit * std_error
        upper_cv = mean_h0 + z_crit * std_error

        verdict = (
            "Fail to Reject H0"
            if lower_cv <= sample_avg <= upper_cv
            else "Reject H0"
        )

        return {
            "Test Type": "Two-tailed",
            "Critical z": z_crit,
            "Lower CV": lower_cv,
            "Upper CV": upper_cv,
            "Sample Mean": sample_avg,
            "\nDecision": verdict
        }

    # RIGHT-TAILED TEST
    elif test_type == 2:
        z_crit = norm.ppf(1 - sig_level)
        upper_cv = mean_h0 + z_crit * std_error

        verdict = (
            "Fail to Reject H0"
            if sample_avg <= upper_cv
            else "Reject H0"
        )

        return {
            "Test Type": "Right-tailed",
            "Critical z": z_crit,
            "Upper CV": upper_cv,
            "Sample Mean": sample_avg,
            "\nDecision": verdict
        }

    # LEFT-TAILED TEST
    elif test_type == 3:
        z_crit = norm.ppf(1 - sig_level)
        lower_cv = mean_h0 - z_crit * std_error

        verdict = (
            "Fail to Reject H0"
            if sample_avg >= lower_cv
            else "Reject H0"
        )

        return {
            "Test Type": "Left-tailed",
            "Critical z": z_crit,
            "Lower CV": lower_cv,
            "Sample Mean": sample_avg,
            "\nDecision": verdict
        }

    else:
        raise ValueError("test_type must be 1 (two), 2 (right), or 3 (left)")


if __name__ == "__main__":
    print("Z-Test Hypothesis Testing Using Critical Value Method\n")

    pop_std = float(input("Enter population standard deviation: "))
    mean_h0 = float(input("Enter null hypothesis mean (μ₀): "))
    sample_avg = float(input("Enter observed sample mean: "))
    size_n = int(input("Enter number of observations: "))
    sig_level = float(input("Enter significance level: "))

    print("\nChoose hypothesis test:")
    print("1. Two-tailed test (H₁: μ ≠ μ₀)")
    print("2. Right-tailed test (H₁: μ > μ₀)")
    print("3. Left-tailed test (H₁: μ < μ₀)")

    test_type = int(input("Enter option (1/2/3): "))

    print("\nTest Results:\n")

    output = z_test_critical(
        mean_h0, sample_avg, pop_std, size_n, sig_level, test_type
    )

    for key, value in output.items():
        print(f"{key}: {value}")

    print("\n")